# Question 8

#### a) Find the class priors using the training set. Report the prior probabilities of a pixel being ‘skin’ or being ‘non-skin’.

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import sys
import glob
from PIL import Image
from io import BytesIO
import os.path

In [29]:
path = "./inputs/P8/pratheepan/"
number_of_pix = 0
white_class = 0
black_class = 0
for filename in glob.glob(path + 'train/set1/images/*.jpg'): #assuming gif
    im_name = os.path.basename(filename)[:-4]
    # print (im_name)
    im=Image.open(filename)
    ground_truth = Image.open(path + 'train/set1/groundtruth/'+im_name+".png")

    a = np.asarray(im)
    g = np.asarray(ground_truth)


    for i in range(0, len(g)):
        for j in range(0, len(g[0])):
            number_of_pix += 1
            if g[i][j][0] ==0:
                black_class +=1
            else:
                white_class +=1



In [30]:

white_prior = white_class/number_of_pix
black_prior = black_class/number_of_pix
print ("probability of white_class", white_prior)
print ("probability of Black class", black_prior)

probability of white_class 0.27737971103915027
probability of Black class 0.7226202889608497


#### b) If we decide to model the class-conditional probability density of each class using a univariate Gaussian, what would be the mean and variance of both class-conditional densities?

In [31]:
number_of_pix = 0
white_class = []
black_class = []
for filename in glob.glob(path + 'train/set1/images/*.jpg'): #assuming gif
    im_name = os.path.basename(filename)[:-4]
    # print (im_name)
    im=Image.open(filename)
    ground_truth = Image.open(path + 'train/set1/groundtruth/'+im_name+".png")

    a = np.asarray(im)
    g = np.asarray(ground_truth)


    for i in range(0, len(g)):
        for j in range(0, len(g[0])):
            number_of_pix += 1
            if g[i][j][0] ==0:
                black_class.append([a[i][j][0], a[i][j][1],a[i][j][2]])
            else:
                white_class.append([a[i][j][0], a[i][j][1],a[i][j][2]])


In [13]:
white_class= np.asarray(white_class)
black_class= np.asarray(black_class)

In [26]:
average = np.average(white_class, axis=0)
print ("For Skin class \n -------------")
print ("Mean\n", average)
print ("-------------")
# normalized_white_class = white_class - average
# normalized_white_class_vectors = normalized_white_class.reshape(-1,1)
print ("Covariance Matrix")
cov = np.cov(white_class.T)
print (cov)

For Skin class 
 -------------
Mean
 [190.49728975 140.99640091 112.06415329]
-------------
Covariance Matrix
[[1938.29686227 1930.01997348 1845.39526753]
 [1930.01997348 2366.6346144  2441.33298208]
 [1845.39526753 2441.33298208 2676.98597279]]


In [27]:
average = np.average(black_class, axis=0)
print ("For Non_Skin class \n -------------")
print ("Mean\n", average)
print ("-------------")
# normalized_white_class = white_class - average
# normalized_white_class_vectors = normalized_white_class.reshape(-1,1)
print ("Covariance Matrix")
cov = np.cov(black_class.T)
print (cov)

For Non_Skin class 
 -------------
Mean
 [128.633646   105.51495792  95.05248156]
-------------
Covariance Matrix
[[7822.84660232 6739.88356763 6287.91273555]
 [6739.88356763 7086.64480118 6897.54707591]
 [6287.91273555 6897.54707591 7098.99338834]]


#### c) Classify the pixels in image ‘mad_trump.jpg’ and ‘trump_long_tie.jpg’ (Figure 6) and display the results, i.e. the groundtruth image.

In [ ]:
trump = Image.open("./inputs/P8/mad_trump.jpg")
bias = np.log(pr)
output = np.zeros(len(trump), len(trump[0]))
for i in range(0, len(trump)):
    for j in range(0, len(trump[0])):
        
        
# a = np.asarray(trump)
# 
# for filename in glob.glob(path + 'train/set1/images/*.jpg'): #assuming gif
# 
#     im_name = os.path.basename(filename)[:-4]
#     # print (im_name)
#     im=Image.open(filename)
#     ground_truth = Image.open(path + 'train/set1/groundtruth/'+im_name+".png")

#### d) Repeat the previous part with a MDC classifier. Display and compare the results.

#### e) Classify the pixels of the images in ‘test’ folder and report the overall test error.

#### f) Compute a confusion matrix for this classifier.

#### g) Calculate the Bayes error.

#### h) Draw a ROC curve to visualise the performance of the classification.

#### i) Repeat the previous parts, this time considering all training images (‘set1’ and ‘set2’). Compare the results.